=== caubinhphu/QLKS_H2O_XML_2/public/data/QLKS_H2O.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:simpleType name="sdt">
        <xs:restriction base="xs:string">
            <xs:pattern value="0\d{9}"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="mamau">
        <xs:restriction base="xs:string">
            <xs:pattern value="#[0-9a-f]{3,}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="QLKS_H2O">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="LOAIPHONG" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MA_LOAIPHONG">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z]{2,3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TEN_LOAIPHONG" type="xs:string"/>
                            <xs:element name="KICHTHUOC" type="xs:unsignedShort"/>
                            <xs:element name="MAMAU" type="mamau"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="VATTU" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MA_VATTU">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TEN_VATTU" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="DICHVU" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MA_DICHVU">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z]{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TEN_DICHVU" type="xs:string"/>
                            <xs:element name="GIA_DICHVU" type="xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="VATTU_LOAIPHONG" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MA_VATTU" type="xs:string"/>
                            <xs:element name="MA_LOAIPHONG" type="xs:string"/>
                            <xs:element name="SOLUONG" type="xs:unsignedByte"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="TRANGTHAI_PHONG" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MA_TRANGTHAI">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="[A-Z]{2}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="TEN_TRANGTHAI" type="xs:string"/>
                            <xs:element name="MAMAU" type="mamau"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="PHONG" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MAPHONG">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{3}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MA_LOAIPHONG" type="xs:string"/>
                            <xs:element name="GIAPHONG" type="xs:positiveInteger"/>
                            <xs:element name="MA_TRANGTHAI" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="KHACH" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MA_KHACH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{9}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="HOTEN_KHACH" type="xs:string"/>
                            <xs:element name="GIOITINH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Nam"/>
                                        <xs:enumeration value="Nữ"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NGAYSINH" type="xs:date"/>
                            <xs:element name="CMND_PASSPORT" type="xs:string"/>
                            <xs:element name="DIENTHOAI" type="sdt"/>
                            <xs:element name="QUOCTICH" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="NHANVIEN" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="MA_NHANVIEN">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="NV\d{2,}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="PASSWORD" type="xs:string"/>
                            <xs:element name="HOTEN_NHANVIEN" type="xs:string"/>
                            <xs:element name="GIOITINH">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Nam"/>
                                        <xs:enumeration value="Nữ"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="NGAYSINH" type="xs:date"/>

                            <xs:element name="CMND">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{9}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="DIENTHOAI" type="sdt"/>
                            <xs:element name="DIACHI" type="xs:string"/>
                            <xs:element name="EMAIL">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\w{2,}@\w{2,}\.\w{2,}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="BOPHAN">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:enumeration value="Lễ tân"/>
                                        <xs:enumeration value="Kế toán"/>
                                        <xs:enumeration value="Quản lý"/>
                                        <xs:enumeration value="Vật tư"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="PHIEU_THUEPHONG" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SO_PHIEU">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:pattern value="\d{9}"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="MAKHACH" type="xs:string"/>
                            <xs:element name="MA_NHANVIEN" type="xs:string"/>
                            <xs:element name="NGAYLAP_PHIEU" type="xs:date"/>
                            <xs:element name="NGAYDEN" type="xs:date"/>
                            <xs:element name="NGAYDI" type="xs:date"/>
                        </xs:sequence>
                        <xs:attribute name="DATRAPHONG" type="xs:boolean" default="0"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="CHITIET_THUEPHONG" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SO_PHIEU" type="xs:string"/>
                            <xs:element name="MAPHONG" type="xs:string"/>
                            <xs:element name="SONGUOI" type="xs:unsignedByte"/>
                            <xs:element name="GIAPHONG" type="xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="CT_THUE_DICHVU" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="SO_PHIEU" type="xs:string"/>
                            <xs:element name="MA_DICHVU" type="xs:string"/>
                            <xs:element name="SOLUONG" type="xs:unsignedByte"/>
                            <xs:element name="GIA_DICHVU" type="xs:positiveInteger"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="LPK">
            <xs:selector xpath="LOAIPHONG"/>
            <xs:field xpath="MA_LOAIPHONG"/>
        </xs:key>
        <xs:key name="VTK">
            <xs:selector xpath="VATTU"/>
            <xs:field xpath="MA_VATTU"/>
        </xs:key>
        <xs:key name="VTLPK">
            <xs:selector xpath="VATTU_LOAIPHONG"/>
            <xs:field xpath="MA_VATTU"/>
            <xs:field xpath="MA_LOAIPHONG"/>
        </xs:key>
        <xs:keyref name="VTLPKR1" refer="VTK">
            <xs:selector xpath="VATTU_LOAIPHONG"/>
            <xs:field xpath="MA_VATTU"/>
        </xs:keyref>
        <xs:keyref name="VTLPKR2" refer="LPK">
            <xs:selector xpath="VATTU_LOAIPHONG"/>
            <xs:field xpath="MA_LOAIPHONG"/>
        </xs:keyref>
        <xs:key name="TTK">
            <xs:selector xpath="TRANGTHAI_PHONG"/>
            <xs:field xpath="MA_TRANGTHAI"/>
        </xs:key>
        <xs:key name="PK">
            <xs:selector xpath="PHONG"/>
            <xs:field xpath="MAPHONG"/>
        </xs:key>
        <xs:keyref name="PKR" refer="LPK">
            <xs:selector xpath="PHONG"/>
            <xs:field xpath="MA_LOAIPHONG"/>
        </xs:keyref>
        <xs:keyref name="PKR2" refer="TTK">
            <xs:selector xpath="PHONG"/>
            <xs:field xpath="MA_TRANGTHAI"/>
        </xs:keyref>
        <xs:key name="KHK">
            <xs:selector xpath="KHACH"/>
            <xs:field xpath="MA_KHACH"/>
        </xs:key>
        <xs:key name="NVK">
            <xs:selector xpath="NHANVIEN"/>
            <xs:field xpath="MA_NHANVIEN"/>
        </xs:key>
        <xs:key name="DVK">
            <xs:selector xpath="DICHVU"/>
            <xs:field xpath="MA_DICHVU"/>
        </xs:key>
        <xs:key name="TPK">
            <xs:selector xpath="PHIEU_THUEPHONG"/>
            <xs:field xpath="SO_PHIEU"/>
        </xs:key>
        <xs:keyref name="TPKR1" refer="KHK">
            <xs:selector xpath="PHIEU_THUEPHONG"/>
            <xs:field xpath="MAKHACH"/>
        </xs:keyref>
        <xs:keyref name="TPKR2" refer="NVK">
            <xs:selector xpath="PHIEU_THUEPHONG"/>
            <xs:field xpath="MA_NHANVIEN"/>
        </xs:keyref>
        <xs:key name="CTTPK">
            <xs:selector xpath="CHITIET_THUEPHONG"/>
            <xs:field xpath="SO_PHIEU"/>
            <xs:field xpath="MAPHONG"/>
        </xs:key>
        <xs:keyref name="CTTPKR1" refer="TPK">
            <xs:selector xpath="CHITIET_THUEPHONG"/>
            <xs:field xpath="SO_PHIEU"/>
        </xs:keyref>
        <xs:keyref name="CTTPKR2" refer="PK">
            <xs:selector xpath="CHITIET_THUEPHONG"/>
            <xs:field xpath="MAPHONG"/>
        </xs:keyref>
        <xs:key name="CTDVK">
            <xs:selector xpath="CT_THUE_DICHVU"/>
            <xs:field xpath="SO_PHIEU"/>
            <xs:field xpath="MA_DICHVU"/>
        </xs:key>
        <xs:keyref name="CTDVKR1" refer="TPK">
            <xs:selector xpath="CT_THUE_DICHVU"/>
            <xs:field xpath="SO_PHIEU"/>
        </xs:keyref>
        <xs:keyref name="CTDVKR2" refer="DVK">
            <xs:selector xpath="CT_THUE_DICHVU"/>
            <xs:field xpath="MA_DICHVU"/>
        </xs:keyref>
    </xs:element>
</xs:schema>

=== caubinhphu/QLKS_H2O_XML_2/public/data/QLKS_H2O.xml
<?xml version="1.0" encoding="UTF-8"?>
<QLKS_H2O xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="QLKS_H2O.xsd">
    <LOAIPHONG>
        <MA_LOAIPHONG>SGL</MA_LOAIPHONG>
        <TEN_LOAIPHONG>PHÒNG ĐƠN</TEN_LOAIPHONG>
        <KICHTHUOC>25</KICHTHUOC>
        <MAMAU>#2060d0</MAMAU>
    </LOAIPHONG>
    <LOAIPHONG>
        <MA_LOAIPHONG>TWN</MA_LOAIPHONG>
        <TEN_LOAIPHONG>PHÒNG HAI GIƯỜNG ĐƠN</TEN_LOAIPHONG>
        <KICHTHUOC>30</KICHTHUOC>
        <MAMAU>#20d027</MAMAU>
    </LOAIPHONG>
    <LOAIPHONG>
        <MA_LOAIPHONG>TRP</MA_LOAIPHONG>
        <TEN_LOAIPHONG>PHÒNG BA GIƯỜNG ĐƠN</TEN_LOAIPHONG>
        <KICHTHUOC>50</KICHTHUOC>
        <MAMAU>#d04a20</MAMAU>
    </LOAIPHONG>
    <LOAIPHONG>
        <MA_LOAIPHONG>DBL</MA_LOAIPHONG>
        <TEN_LOAIPHONG>PHÒNG GIƯỜNG ĐÔI</TEN_LOAIPHONG>
        <KICHTHUOC>50</KICHTHUOC>
        <MAMAU>#d04a20</MAMAU>
    </LOAIPHONG>
    <LOAIPHONG>
        <MA_LOAIPHONG>DLX</MA_LOAIPHONG>
        <TEN_LOAIPHONG>PHÒNG GIƯỜNG ĐÔI CÓ VIEW</TEN_LOAIPHONG>
        <KICHTHUOC>50</KICHTHUOC>
        <MAMAU>#13dad2</MAMAU>
    </LOAIPHONG>
    <LOAIPHONG>
        <MA_LOAIPHONG>FAM</MA_LOAIPHONG>
        <TEN_LOAIPHONG>PHÒNG GIA ĐÌNH</TEN_LOAIPHONG>
        <KICHTHUOC>70</KICHTHUOC>
        <MAMAU>#dd23de</MAMAU>
    </LOAIPHONG>
    <VATTU>
        <MA_VATTU>GDN</MA_VATTU>
        <TEN_VATTU>GIƯỜNG ĐƠN</TEN_VATTU>
    </VATTU>
    <VATTU>
        <MA_VATTU>GDB</MA_VATTU>
        <TEN_VATTU>GIƯỜNG ĐÔI</TEN_VATTU>
    </VATTU>
    <VATTU>
        <MA_VATTU>TVI</MA_VATTU>
        <TEN_VATTU>TI VI</TEN_VATTU>
    </VATTU>
    <VATTU>
        <MA_VATTU>TMA</MA_VATTU>
        <TEN_VATTU>TỦ MÁT</TEN_VATTU>
    </VATTU>
    <VATTU>
        <MA_VATTU>MSA</MA_VATTU>
        <TEN_VATTU>MÁY SẤY</TEN_VATTU>
    </VATTU>
    <VATTU>
        <MA_VATTU>MDH</MA_VATTU>
        <TEN_VATTU>MÁY ĐIỀU HÒA</TEN_VATTU>
    </VATTU>
    <VATTU>
        <MA_VATTU>KHT</MA_VATTU>
        <TEN_VATTU>KHĂN TẮM</TEN_VATTU>
    </VATTU>
    <VATTU>
        <MA_VATTU>DEP</MA_VATTU>
        <TEN_VATTU>DÉP</TEN_VATTU>
    </VATTU>
    <VATTU>
        <MA_VATTU>GOI</MA_VATTU>
        <TEN_VATTU>GỐI</TEN_VATTU>
    </VATTU>
    <VATTU>
        <MA_VATTU>CHA</MA_VATTU>
        <TEN_VATTU>CHĂN</TEN_VATTU>
    </VATTU>
    <VATTU>
        <MA_VATTU>BAN</MA_VATTU>
        <TEN_VATTU>BÀN</TEN_VATTU>
    </VATTU>
    <VATTU>
        <MA_VATTU>TUR</MA_VATTU>
        <TEN_VATTU>TỦ</TEN_VATTU>
    </VATTU>
    <VATTU>
        <MA_VATTU>NET</MA_VATTU>
        <TEN_VATTU>THIẾT BỊ MẠNG</TEN_VATTU>
    </VATTU>
    <DICHVU>
        <MA_DICHVU>XEM</MA_DICHVU>
        <TEN_DICHVU>THUÊ XE MÁY</TEN_DICHVU>
        <GIA_DICHVU>130000</GIA_DICHVU>
    </DICHVU>
    <DICHVU>
        <MA_DICHVU>ANS</MA_DICHVU>
        <TEN_DICHVU>ĂN SÁNG</TEN_DICHVU>
        <GIA_DICHVU>40000</GIA_DICHVU>
    </DICHVU>
    <DICHVU>
        <MA_DICHVU>DLI</MA_DICHVU>
        <TEN_DICHVU>DU LỊCH</TEN_DICHVU>
        <GIA_DICHVU>500000</GIA_DICHVU>
    </DICHVU>
    <DICHVU>
        <MA_DICHVU>TXM</MA_DICHVU>
        <TEN_DICHVU>ĐẶT TAXI TỚI SÂN BAY</TEN_DICHVU>
        <GIA_DICHVU>100000</GIA_DICHVU>
    </DICHVU>
    <DICHVU>
        <MA_DICHVU>TXH</MA_DICHVU>
        <TEN_DICHVU>ĐẶT TAXI TỚI BẾN XE</TEN_DICHVU>
        <GIA_DICHVU>100000</GIA_DICHVU>
    </DICHVU>
    <DICHVU>
        <MA_DICHVU>NUO</MA_DICHVU>
        <TEN_DICHVU>NƯỚC SUỐI</TEN_DICHVU>
        <GIA_DICHVU>10000</GIA_DICHVU>
    </DICHVU>
    <DICHVU>
        <MA_DICHVU>CLA</MA_DICHVU>
        <TEN_DICHVU>COCACOLA LON</TEN_DICHVU>
        <GIA_DICHVU>200000</GIA_DICHVU>
    </DICHVU>
    <DICHVU>
        <MA_DICHVU>BIA</MA_DICHVU>
        <TEN_DICHVU>BIA</TEN_DICHVU>
        <GIA_DICHVU>40000</GIA_DICHVU>
    </DICHVU>
    <DICHVU>
        <MA_DICHVU>TTP</MA_DICHVU>
        <TEN_DICHVU>TRANG TRÍ PHÒNG</TEN_DICHVU>
        <GIA_DICHVU>200000</GIA_DICHVU>
    </DICHVU>
    <DICHVU>
        <MA_DICHVU>GUI</MA_DICHVU>
        <TEN_DICHVU>GIẶT ỦI</TEN_DICHVU>
        <GIA_DICHVU>50000</GIA_DICHVU>
    </DICHVU>
    <VATTU_LOAIPHONG>
        <MA_VATTU>GDN</MA_VATTU>
        <MA_LOAIPHONG>SGL</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>GDN</MA_VATTU>
        <MA_LOAIPHONG>TWN</MA_LOAIPHONG>
        <SOLUONG>2</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>GDN</MA_VATTU>
        <MA_LOAIPHONG>TRP</MA_LOAIPHONG>
        <SOLUONG>3</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>GDN</MA_VATTU>
        <MA_LOAIPHONG>DBL</MA_LOAIPHONG>
        <SOLUONG>0</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>GDN</MA_VATTU>
        <MA_LOAIPHONG>DLX</MA_LOAIPHONG>
        <SOLUONG>0</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>GDN</MA_VATTU>
        <MA_LOAIPHONG>FAM</MA_LOAIPHONG>
        <SOLUONG>2</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>GDB</MA_VATTU>
        <MA_LOAIPHONG>SGL</MA_LOAIPHONG>
        <SOLUONG>0</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>GDB</MA_VATTU>
        <MA_LOAIPHONG>TWN</MA_LOAIPHONG>
        <SOLUONG>0</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>GDB</MA_VATTU>
        <MA_LOAIPHONG>TRP</MA_LOAIPHONG>
        <SOLUONG>0</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>GDB</MA_VATTU>
        <MA_LOAIPHONG>DBL</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>GDB</MA_VATTU>
        <MA_LOAIPHONG>DLX</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>GDB</MA_VATTU>
        <MA_LOAIPHONG>FAM</MA_LOAIPHONG>
        <SOLUONG>2</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>TVI</MA_VATTU>
        <MA_LOAIPHONG>SGL</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>TVI</MA_VATTU>
        <MA_LOAIPHONG>TWN</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>TVI</MA_VATTU>
        <MA_LOAIPHONG>TRP</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>TVI</MA_VATTU>
        <MA_LOAIPHONG>DBL</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>TVI</MA_VATTU>
        <MA_LOAIPHONG>DLX</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>TVI</MA_VATTU>
        <MA_LOAIPHONG>FAM</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>TMA</MA_VATTU>
        <MA_LOAIPHONG>SGL</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>TMA</MA_VATTU>
        <MA_LOAIPHONG>TWN</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>TMA</MA_VATTU>
        <MA_LOAIPHONG>TRP</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>TMA</MA_VATTU>
        <MA_LOAIPHONG>DBL</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>TMA</MA_VATTU>
        <MA_LOAIPHONG>DLX</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>TMA</MA_VATTU>
        <MA_LOAIPHONG>FAM</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>MSA</MA_VATTU>
        <MA_LOAIPHONG>SGL</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>MSA</MA_VATTU>
        <MA_LOAIPHONG>TWN</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>MSA</MA_VATTU>
        <MA_LOAIPHONG>TRP</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>MSA</MA_VATTU>
        <MA_LOAIPHONG>DBL</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>MSA</MA_VATTU>
        <MA_LOAIPHONG>DLX</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>MSA</MA_VATTU>
        <MA_LOAIPHONG>FAM</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>MDH</MA_VATTU>
        <MA_LOAIPHONG>SGL</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>MDH</MA_VATTU>
        <MA_LOAIPHONG>TWN</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>MDH</MA_VATTU>
        <MA_LOAIPHONG>TRP</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>MDH</MA_VATTU>
        <MA_LOAIPHONG>DBL</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>MDH</MA_VATTU>
        <MA_LOAIPHONG>DLX</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>MDH</MA_VATTU>
        <MA_LOAIPHONG>FAM</MA_LOAIPHONG>
        <SOLUONG>1</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>KHT</MA_VATTU>
        <MA_LOAIPHONG>SGL</MA_LOAIPHONG>
        <SOLUONG>2</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>KHT</MA_VATTU>
        <MA_LOAIPHONG>TWN</MA_LOAIPHONG>
        <SOLUONG>4</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>KHT</MA_VATTU>
        <MA_LOAIPHONG>TRP</MA_LOAIPHONG>
        <SOLUONG>6</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
        <MA_VATTU>KHT</MA_VATTU>
        <MA_LOAIPHONG>DBL</MA_LOAIPHONG>
        <SOLUONG>4</SOLUONG>
    </VATTU_LOAIPHONG>
    <VATTU_LOAIPHONG>
